version: '3'
services:
    node:
        image: node:14.14-stretch
        ports:
            - 1337:1337
        tty: true
        working_dir: /var/www/zogs/surfwall
        volumes:
            - /f/sites/zogs/surfwall/:/var/www/zogs/surfwall